spring.application.name=masternote


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5434/masternotedb
spring.datasource.username=postgres
spring.datasource.password=Nguyen_Anh12

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.ai.google.genai.api-key=AIzaSyCILdIIn_V-AjgEMxnCKOAqaJDqhN46Tww
spring.ai.google.genai.chat.options.model=gemini-2.5-flash


#JWT
app.jwt.secret=1234567890qwertyuiopasdfghjklzxcvbnm1234567890
app.jwt.expiration-ms=86400000
springdoc.swagger-ui.path=/swagger-ui.html


