spring.application.name=masternote

# DATABASE (PostgreSQL / Supabase)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/masternotedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Nguyen_Anh12}

spring.jpa.hibernate.ddl-auto=update

# LOGGING (t?t SQL log trên server)
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SHOW_SQL:true}

# REDIS
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# GEMINI AI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html